- name: Install and Configure Portainer Agent
  hosts: all
  become: true
  tasks:

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Portainer Agent
      docker_container:
        name: portainer_agent
        image: portainer/agent:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "9001:9001"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"
